zigwheel_url_cities = ['Mumbai']




# zigwheel_url_cities  =['Mumbai', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Ahmedabad', 'Pune', 'Chandigarh', 'Gurgaon', 'Noida', 'Ghaziabad', 
# 'Faridabad', 'Adoor', 'Agra', 'Ahmednagar', 'Ajmer', 'Akluj', 'Akola', 'Alappuzha', 'Alibag', 'Aligarh', 'Allahabad', 'Aluva', 'Alwar', 'Ambala', 'Ambedkar-Nagar', 'Ambikapur', 
# 'Amravati', 'Amreli', 'Amritsar', 'Anand', 'Anantnag', 'Angul', 'Asansol', 'Aurangabad', 'Avadi', 'Badaun', 'Bagalkot', 'Bahadurgarh', 'Bahadurpur', 'Balasore', 
# 'Ballabhgarh', 'Banaskantha', 'Bankura', 'Barabanki', 'Baramati', 'Barasat', 'Bareilly', 'Barnala', 'Barrackpur', 'Basti', 'Batala', 'Bathinda', 'Bawal', 'Beed', 'Begusarai',
# 'Belgaum', 'Bellary', 'Bengaluru', 'Bettiah', 'Betul', 'Bewar', 'Bhagalpur', 'Bhagur', 'Bhandara', 'Bharatpur', 'Bhavnagar', 'Bhilai', 'Bhilwara', 'Bhimavaram', 'Bhiwadi',
# 'Bhiwandi', 'Bhiwani', 'Bhojpur', 'Bhopal', 'Bhubaneswar', 'Bijnor', 'Bikaner', 'Bilaspur', 'Bilaspur-HP', 'Boisar', 'Bokaro', 'Bokaro-Steel-City', 'Bolangir', 'Bommanahalli',
# 'Bulandshahr', 'Buldhana', 'Bundi', 'Burdwan', 'Calicut', 'Chamba', 'Chandrapur', 'Changanassery', 'Chhindwara', 'Chiplun', 'Chitradurga', 'Chittoor', 'Chittorgarh', 'Churu', 
# 'Cochin', 'Coimbatore', 'Cuddalore', 'Cuttack', 'Dakshina-Kannada', 'Daman', 'Darjeeling', 'Dasarahalli', 'Dausa', 'Davangere', 'Deesa', 'Dehradun', 'Dewas', 'Dhanbad', 
# 'Dharmapuri', 'Dharwad', 'Dhule', 'Dibrugarh', 'Dombivali', 'Durg', 'Durgapur', 'East-Godavari', 'Ernakulam', 'Etah', 'Etawah', 'Faizabad', 'Faridkot', 'Firozpur', 'Gadag', 
# 'Gandhidham', 'Gandhinagar', 'Ganganagar', 'Gangapur', 'Gangavathi', 'Gangtok', 'Gautam-Buddha-Nagar', 'Gaya', 'Ghazipur', 'Goa', 'Gorakhpur', 'Goregaon', 'Gulbarga', 'Guntur', 
# 'Gurdaspur', 'Guwahati', 'Gwalior', 'Hajipur', 'Haldwani', 'Hanumangarh', 'Hardoi', 'Hariana', 'Haridwar', 'Hassan', 'Hathras', 'Hazaribagh', 'Hisar', 'Hooghly', 'Hoshangabad', 
# 'Hoshiarpur', 'Hosur', 'Howrah', 'Hubli', 'Iduki', 'Indore', 'Jabalpur', 'Jagraon', 'Jaipur', 'Jaisalmer', 'Jajapur', 'Jalandhar', 'Jalgaon', 'Jalna', 'Jammu', 'Jamnagar', 
# 'Jamshedpur', 'Jeypore', 'Jhajjar', 'Jhalawar', 'Jhansi', 'Jhunjhunu', 'Jind', 'Jodhpur', 'Jorhat', 'Junagadh', 'Kaithal', 'Kalpakkam', 'Kalyan', 'Kalyani', 'Kamrup', 'Kannur', 
# 'Kanpur', 'Kanyakumari', 'Karjat', 'Karnal', 'Karunagapally', 'Kasaragod', 'Katghora', 'Katni', 'Khammam', 'Khandwa', 'Kheda', 'Kodungallur', 'Kolar', 'Kolhapur', 'Kollam', 
# 'Koothattukulam', 'Korba', 'Kota', 'Kotputli', 'Kottarakara', 'Kottayam', 'Kovur', 'Kozhikode', 'Krishna', 'Kuchchh', 'Kullu', 'Kunnamkulam', 'Kurukshetra', 'Latur', 'Loni', 
# 'Lucknow', 'Ludhiana', 'Madgaon', 'Madurai', 'Mahendragarh', 'Mahuva', 'Malappuram', 'Malda', 'Malegaon', 'Mandapam', 'Mandya', 'Mangalore', 'Margao', 'Mathura', 'Mau', 
# 'Mavelikkara', 'Medak', 'Medinipur', 'Meerut', 'Mehnagar', 'Mehsana', 'Midnapur', 'Mirzapur', 'Moga', 'Mohali', 'Moradabad', 'Motihari', 'Muktsar', 'Muvattupuzha', 'Muzaffarnagar',
# 'Muzaffarpur', 'Mysore', 'Nadiad', 'Nagapattinam', 'Nagaur', 'Nagercoil', 'Nagpur', 'Nainital', 'Nanded', 'Nandigama', 'Narnaul', 'Nashik', 'Navi-Mumbai', 'Navsari', 'Nawanshahr',
# 'Nedumangad', 'Nellore', 'Neyyattinkara', 'Nizamabad', 'North-24-Parganas', 'North-Goa', 'Nuh', 'Other', 'Palai', 'Palakkad', 'Palanpur', 'Pali', 'Palwal', 'Panchkula', 'Panipat',
# 'Panvel', 'Paravoor', 'Paschimi-Singhbhum', 'Pathanamthitta', 'Pathankot', 'Patiala', 'Patna', 'Pen', 'Perinthalmanna', 'Perumbavoor', 'Phagwara', 'Pimpri-Chinchwad', 
# 'Pinjore', 'Pondicherry', 'Port-Blair', 'Prakasam', 'Puri', 'Purnia', 'Pusad', 'Rae-Bareli', 'Raichur', 'Raigarh', 'Raipur', 'Raisinghnagar', 'Rajkot', 'Ramanathapuram', 
# 'Ramapuram', 'Ranchi', 'Ranga-Reddy', 'Ratlam', 'Ratnagiri', 'Rewari', 'Rohtak', 'Rohtas', 'Roorkee', 'Rudrapur', 'Sabarkantha', 'Sagar', 'Saharanpur', 'Salem', 'Samana', 
# 'Samastipur', 'Samba', 'Sambalpur', 'Sangli', 'Sangrur', 'Sasaram', 'Satara', 'Satna', 'Secunderabad', 'Shahjahanpur', 'Shillong', 'Shimla', 'Shivpuri', 'Sholinganallur', 
# 'Shrirampur', 'Sikar', 'Silchar', 'Siliguri', 'Sindhudurg', 'Sirsa', 'Sirsi', 'Siwan', 'Solan', 'Solapur', 'Sonepat', 'Sonipat', 'South-24-Parganas', 'South-Goa', 
# 'Sri-Ganganagar', 'Srinagar', 'Sultanpur', 'Sundergarh', 'Surat', 'Suri', 'Tanda', 'Tellicherry', 'Thane', 'Thanjavur', 'Thiruvalla', 'Thiruvananthapuram', 'Thodupuzha', 
# 'Thrissur', 'Tiruchirappalli', 'Tirunelveli', 'Tirupati', 'Tirupur', 'Tirur', 'Tiruvallur', 'Trichur', 'Trichy', 'Tumkur', 'Udaipur', 'Udham-Singh-Nagar', 'Ujjain', 'Ulhasnagar', 
# 'Una', 'Unnao', 'Uran', 'Vadgaon', 'Vadodara', 'Vaikom', 'Valsad', 'Vapi', 'Varanasi', 'Vasai', 'Vasco', 'Vashi', 'Vellore', 'Virar', 'Virudhunagar', 'Visakhapatnam', 'Warangal', 
# 'Wardha', 'Yamuna-Nagar', 'Yavatmal', 'Zirakpur']

Cartrade_url_cities = ['Surat', 'Jalandhar', 'Nadia', 
'Moga', 'Bhopal', 'Zirakpur', 'Jammu', 'Varanasi', 'Khanna', 'Mathura', 'Trivandrum', 'Srinagar', 'Panchkula', 
'Ratnagiri', 'Vapi', 'Ajmer', 'Nagpur', 'Gwalior', 'Saharanpur', 'Port Blair', 'Mohali', 'Ahmednagar', 'Sangli',
 'Nanded', 'Bharuch', 'Pathankot', 'Kasaragod', 'Surendranagar', 'Kanpur', 'Ujjain', 'Visakhapatnam', 'Gandhinagar', 
 'Kannur', 'Agra', 'Durgapur', 'Ranchi', 'Shillong', 'Amritsar', 'Coimbatore', 'Ludhiana', 'Jodhpur', 'Karnal', 
 'Amravati', 'Kurukshetra', 'Meerut', 'Kota', 'Lucknow', 'Sivakasi', 'Siliguri', 'Kolhapur', 'Bhilai', 'Tirunelveli', 
 'Thoothukudi', 'Nashik', 'Anand', 'Dhanbad', 'Firozabad', 'Solapur', 'Vadodara', 'Ambala', 'Patna', 'Tiruvallur', 
 'Visnagar', 'Gulbarga', 'Erode', 'Dibrugarh', 'Shimla', 'Howrah', 'Jaipur', 'Gandhidham', 'Allahabad', 'Aurangabad',
  'Haldwani', 'Vijayawada', 'Tirupur', 'Thanjavur', 'Dharwad', 'Panipat', 'Belgaum', 'Rajkot', 'Bhuj', 'Salem',
   'Mangalore', 'Nellore', 'Patiala', 'Madurai', 'Hubli', 'Dehradun', 'Kozhikode', 'Jamnagar', 'Guwahati', 
   'Kollam', 'Tiruvalla', 'Bhavnagar', 'Warangal', 'Goa', 'Raipur', 'Udaipur', 'Alwar', 'Thrissur', 'Tirupati',
    'Sikar', 'Jabalpur', 'Gurdaspur', 'Guntur', 'Kottayam', 'Bhubaneswar', 'Tiruchirapalli', 'Bilaspur', 'Malappuram', 
    'Indore', 'Valsad', 'Akola', 'Durg', 'Sri Ganganagar', 'Jamshedpur', 'Mehsana', 'Yamunanagar', 'Cochin', 'New Delhi', 
    'Pune', 'Chennai', 'Navi Mumbai', 'Noida', 'Mumbai', 'Ghaziabad', 'Thane', 'Gurgaon', 'Faridabad', 'Chandigarh', 
    'Kolkata', 'Bangalore', 'Hyderabad', 'Ahmedabad']
